routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

// Route::get('/', function () {
//     return redirect('/dashboard');
// });

Auth::routes(['register' => false]);

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::middleware(['auth', 'role:superadmin'])->namespace('Superadmin')->prefix('superadmin')->name('superadmin.')->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/create', 'AdminController@store')->name('store');
        Route::get('/edit/{admin:username}', 'AdminController@edit')->name('edit');
        Route::post('/edit/{admin}', 'AdminController@update')->name('update');
        Route::post('/delete', 'AdminController@delete')->name('delete2');
        Route::get('/delete/{admin}', 'AdminController@destroy')->name('admin.destroy');
    });

    Route::prefix('staff')->name('staff.')->group(function (){
        Route::get('/','StaffController@index')->name('index');
        Route::get('/create' , 'StaffController@create')->name('create');
        Route::post('/store','StaffController@store')->name('store');
        Route::get('/edit/{staff:username}' , 'StaffController@edit')->name('edit');
        Route::post('/update/{staff}' , 'StaffController@update')->name('update');
        Route::post('/delete2' , 'StaffController@delete2')->name('delete2');
        Route::get('/destroy/{staff}' , 'StaffController@destroy')->name('destroy');
    });
});

app/Http/Controllers/SuperAdmin/AdminController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;
use App\Http\Requests\AdminFormRequest;
use Illuminate\Support\Facades\Session;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = User::role('admin')->get();
        return view('superadmin.admin.index', compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return (view('superadmin.admin.create'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminFormRequest $request)
    {
        $data = [
            'name' => request()->name,
            'username' => request()->username,
            'password' => bcrypt(request()->password),
            'email' => request()->email,
            'address' => request()->address,
            'phone' => request()->phone,
            'gender' => request()->gender,
            'nik' => request()->nik,

        ];

        $staff = User::create($data);
        $staff->assignRole('admin');

        $message = 'Berhasil menambahkan Admin baru';
        Session::flash('admin', $message);

        return redirect(route('superadmin.admin.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $admin)
    {

        return view('superadmin.admin.edit', compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $admin)
    {
        if ($request->password == '') {
            $password = $admin->password;
        } else {
            $password = bcrypt($request->password);
        }

        $data = [
            'name' => request()->name,
            'username' => request()->username,
            'password' => $password,
            'email' => request()->email,
            'address' => request()->address,
            'phone' => request()->phone,
            'gender' => request()->gender,
            'nik' => request()->nik,

        ];

        $admin->update($data);

        $message = 'Berhasil Mengubah Admin';

        Session::flash('admin', $message);

        return redirect(route('superadmin.admin.index'));
    }
    public function destroy(User $admin)
    {
        $admin->delete();

        $message = 'Berhasil Menghapus Admin';

        Session::flash('admin', $message);

        return redirect(route('superadmin.admin.index'));
    }

    public function delete()
    {
        $a = request()->id;

        $staff = User::find($a);
        $staff->delete();

        $staffs = User::role('staff')->get();
        $rs['content'] = View::make('superadmin.staff.partial.content')
            ->with('staffs', $staffs)
            ->render();

        return response($rs);
    }
}

app/Http/Controllers/Superadmin/StaffController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StaffFormRequest;
use App\User;
use App\Models\Area;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class StaffController extends Controller
{
    public function index()
    {
        $staffs = User::role('staff')->get();
        return view('superadmin.staff.index' , compact('staffs'));
    }

    public function create()
    {
        $areas = Area::all();
        return view('superadmin.staff.create', compact('areas'));
    }

    public function store(StaffFormRequest $request)
    {
        $data = [
            'name' => $request->name,
            'username' => $request->username,
            'password' => bcrypt($request->password),
            'email' => $request->email,
            'address' => $request->address,
            'phone' => $request->phone,
            'gender' => $request->gender,
            'area_id' => $request->area,
            'nik' => $request->nik,
        ];

        $staff = User::create($data);
        $staff->assignRole('staff');

        $message = 'Berhasil menambah staff baru';
        Session::flash('staff' , $message);

        return $this->index();

    }

    public function edit(User $staff)
    {
        $areas = Area::all();
        return view('superadmin.staff.edit',compact('staff','areas'));
    }

    public function update(Request $request, User $staff)
    {
             if ($request->password == ' ') {
                  $password = $staff->password;
             } else {
                  $password = bcrypt($request->password);
             }

             $data = [
                'name' => request()->name,
                'username' => request()->username,
                'password' => $password,
                'email' => request()->email,
                'address' => request()->address,
                'phone' => request()->phone,
                'gender' => request()->gender,
                'nik' => request()->nik,
                'area_id' => $request->area
            ];

            $staff->update($data);

            $message = 'Berhasil Mengubah Staff';
            Session::flash('staff', $message);

            return $this->index();
    }


    public function delete2()
    {
        $a = request()->id;

        $staff = User::find($a);
        $staff->delete();

        $admins = User::role('admin')->get();
        $rs['content'] = View::make('superadmin.admin.partial.content')
            ->with('admins', $admins)
            ->render();

        return response($rs);
    }

    public function destroy(User $staff)
    {
        $staff->delete();
        $message = 'Berhasil Menghapus Staff';
        Session::flash('staff', $message);
        return $this->index();
    }

}

resources/views/superadmin/staff/create.blade.php
@extends('layouts.master')

@section('title', 'Tambah Admin')

@section('style')
    <!-- Theme JS files -->
    <script src="/global_assets/js/plugins/forms/selects/select2.min.js"></script>
    <script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>

    <script src="/assets/js/app.js"></script>
    <script src="/global_assets/js/demo_pages/form_layouts.js"></script>
    <!-- /theme JS files -->

@endsection

@section('header')
    <div class="page-header border-bottom-0 pt-5">
        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline border-0">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                    <a href="{{ route('superadmin.admin.index') }}" class="breadcrumb-item">Staff</a>
                    <span class="breadcrumb-item active">Tambah Staff</span>
                </div>

                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>

        <br>
    </div>
@endsection

@section('content')
    <div class="content">

        <!-- Basic layout-->

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center ">

                        <h5 class="card-title">Tambah Staff</h5>



                    </div>

                    <div class="card-body">
                        <form action="{{ route('superadmin.staff.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label>Nama:</label>
                                <input type="text" class="form-control " placeholder="Masukan Nama" name="name"
                                       value="{{ old('name') }}">
                            </div>
                            @error('name')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>NIK:</label>
                                <input type="text" class="form-control " placeholder="Masukan NIK" name="nik"
                                       value="{{ old('nik') }}">
                            </div>
                            @error('nik')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>Username:</label>
                                <input type="text" class="form-control" placeholder="Masukan Username"
                                       name="username" value="{{ old('username') }}">
                            </div>
                            @error('username')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>Password:</label>
                                <input type="password" class="form-control" placeholder="Masukan Password"
                                       name="password">
                            </div>
                            @error('password')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>E-Mail:</label>
                                <input type="email" class="form-control" placeholder="Masukan E-Mail" name="email"
                                       value="{{ old('email') }}">
                            </div>
                            @error('email')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>Telephone:</label>
                                <input type="text" class="form-control" placeholder="Masukan Telephone" name="phone"
                                       name="phone" value="{{ old('phone') }}">
                            </div>
                            @error('phone')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror


                            <div class="form-group">
                                <label>Alamat:</label>
                                <input type="text" class="form-control" placeholder="Masukan Alamat" name="address"
                                       value="{{ old('address') }}">
                            </div>
                            @error('address')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label class="d-block">Jenis Kelamin:</label>

                                <div class="form-check form-check-inline">
                                    <label class="form-check-label">
                                        <input type="radio" value="1" class="form-input-styled" name="gender"
                                               checked data-fouc>
                                        Laki-Laki
                                    </label>
                                </div>

                                <div class="form-check form-check-inline">
                                    <label class="form-check-label">
                                        <input type="radio" value="0" class="form-input-styled" name="gender"
                                               data-fouc>
                                        Perempuan
                                    </label>
                                </div>
                            </div>
                            @error('gender')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close"
                                        data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror

                            <div class="form-group">
                                <label class="d-block">Area :</label>
                                <select name="area">
                                    @foreach($areas as $key => $area)
                                    <option value="{{$area->id}}">{{$area->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="text-right">
                                <a href="{{ route('superadmin.staff.index') }}" class="btn btn-danger"><i
                                            class="icon-backward mr-2"></i>Kembali</a>
                                <button type="submit" class="btn btn-primary">Simpan<i
                                            class="icon-paperplane ml-2"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/superadmin/staff/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Admin')

@section('style')
    <!-- Theme JS files -->
    <script src="/global_assets/js/plugins/forms/selects/select2.min.js"></script>
    <script src="/global_assets/js/plugins/forms/styling/uniform.min.js"></script>

    <script src="/assets/js/app.js"></script>
    <script src="/global_assets/js/demo_pages/form_layouts.js"></script>
    <!-- /theme JS files -->

@endsection

@section('header')
    <div class="page-header border-bottom-0">
        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline border-0">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                    <a href="{{ route('superadmin.admin.index') }}" class="breadcrumb-item">Staff</a>
                    <span class="breadcrumb-item active">Edit Staff</span>
                </div>

                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>

        <br>
    </div>
@endsection

@section('content')
    <div class="content">

        <!-- Basic layout-->

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center ">
                        <h5 class="card-title">Edit Staff</h5>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('superadmin.staff.update', [$staff]) }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label>Nama:</label>
                                <input type="text" class="form-control " name="name" value="{{ $staff->name }}">
                            </div>
                            @error('name')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>NIK:</label>
                                <input type="text" class="form-control " name="nik" value="{{ $staff->nik }}">
                            </div>
                            @error('nik')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>Username:</label>
                                <input type="text" class="form-control" value="{{ $staff->username }}" name="username">
                            </div>
                            @error('username')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>Password:</label>
                                <input type="password" class="form-control" name="password">
                            </div>
                            @error('password')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>E-Mail:</label>
                                <input type="text" class="form-control" value="{{ $staff->email }}" name="email">
                            </div>
                            @error('email')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label>Telephone:</label>
                                <input type="text" class="form-control" value="{{ $staff->phone }}" name="phone" name="phone">
                            </div>
                            @error('phone')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror


                            <div class="form-group">
                                <label>Alamat:</label>
                                <input type="text" class="form-control" value="{{ $staff->address }}" name="address">
                            </div>
                            @error('address')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror
                            <div class="form-group">
                                <label class="d-block">Jenis Kelamin:</label>

                                <div class="form-check form-check-inline">
                                    <label class="form-check-label">
                                        <input type="radio" value="1" class="form-input-styled" name="gender"
                                               {{ $staff->gender == 1 ? 'checked':'' }} data-fouc>
                                        Laki-Laki
                                    </label>
                                </div>

                                <div class="form-check form-check-inline">
                                    <label class="form-check-label">
                                        <input type="radio" value="0" class="form-input-styled" name="gender"
                                               {{ $staff->gender == 0 ? 'checked':'' }} data-fouc>
                                        Perempuan
                                    </label>
                                </div>
                            </div>
                            @error('gender')
                            <div class="alert alert-warning alert-rounded alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                                {{ $message }}
                            </div>

                            @enderror

                            <div class="form-group">
                                <label class="d-block">Area :</label>
                                <div class="form-check form-check-inline">
                                    <select name="area">
                                        @foreach($areas as $area)
                                            <option @if($staff->area_id == $area->id) selected @endif value="{{$area->id}}">{{$area->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

{{--                                <div class="form-check form-check-inline">--}}
{{--                                    <label class="form-check-label">--}}
{{--                                        <input type="radio" value="0" class="form-input-styled" name="area"--}}
{{--                                               {{ $staff->gender == 0 ? 'checked':'' }} data-fouc>--}}
{{--                                        Perempuan--}}
{{--                                    </label>--}}
{{--                                </div>--}}
                            </div>

                            <div class="text-right">
                                <a href="{{ route('superadmin.admin.index') }}" class="btn btn-danger"><i
                                            class="icon-backward mr-2"></i>Kembali</a>
                                <button type="submit" class="btn btn-primary">Simpan<i class="icon-paperplane ml-2"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>




    </div>
@endsection

resources/views/superadmin/staff/index.blade.php
@extends('layouts.master')

@section('title', 'Daftar Admin')

@section('style')
    <!-- Theme JS files -->
    <script src="/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="/global_assets/js/plugins/forms/selects/select2.min.js"></script>

    <script src="/assets/js/app.js"></script>
    <script src="/global_assets/js/demo_pages/datatables_basic.js"></script>
    <!-- /theme JS files -->

@endsection

@section('header')
    <div class="page-header border-bottom-0 pt-5">
        <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline border-0">
            <div class="d-flex">
                <div class="breadcrumb">
                    <a href="{{ route('dashboard') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                    <a href="{{ route('superadmin.staff.index') }}" class="breadcrumb-item">Staff</a>
                    <span class="breadcrumb-item active">Daftar Staff</span>
                </div>

                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>

        <br>
    </div>
@endsection

@section('content')
    <div class="content">

        <!-- Basic datatable -->
        <div class="card">
            <div class="card-header bg-blue-700 header-elements-md-inline">
                <div class="row">
                    <div class="col-md-2">
                        <div class="text-left">
                            <a href="{{ route('superadmin.staff.create') }}" class="btn btn-lg bg-indigo mt-2">Tambah</a>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                    @if(Session::has('staff'))
                        <input type="hidden" id="message" value="{{ session()->get('staff') }}">
                    @endif
                </div>
                <div class="header-elements" style="margin-right: 50%">

                    <h5 class="card-title">Daftar Staff</h5>
                </div>
            </div>

            <div id="content">
                <div id="child">
                    <input type="hidden" id="csrf" value="{{csrf_token()}}">
                    <input type="hidden" id="obj" value="staff">
                    <input type="hidden" id="sum" value="{{ $staffs->count() }}">
                    <table class="table datatable-basic">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>E-Mail</th>
                            <th>Alamat</th>
                            <th>Jenis Kelamin</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($staffs as $key => $staff)
                            <tr>
                                <td scope="row">{!! $loop->iteration !!}</td>
                                <td>{{ \Str::ucfirst($staff->name) }}</>
                                </td>
                                <td>{{ \Str::ucfirst($staff->email) }}</td>
                                <td>{{ \Str::ucfirst($staff->address) }}</td>
                                <td>{{ $staff->gender == 1 ? 'Laki-Laki': 'Perempuan' }}</td>

                                <td style="width: 20%">
                                    <a href="{{ route('superadmin.staff.edit', [$staff]) }}"
                                       class="btn btn-success">Edit</a>
                                     <a href="{{ route('superadmin.staff.destroy', [$staff]) }}" class="btn
                                    btn-danger">Delete</a>
{{--                                    <button class="btn btn-danger delete-item-no" id="hapus_{{ $key }}" data-id="{{ $staff->id }}">Delete</button>--}}
                                    <input type="hidden" id="item_{{ $key }}" value="{{ $staff->id }}"></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection