routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

// Route::get('/', function () {
//     return redirect('/dashboard');
// });

Auth::routes(['register' => false]);

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::middleware(['auth', 'role:superadmin'])->namespace('Superadmin')->prefix('superadmin')->name('superadmin.')->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/create', 'AdminController@store')->name('store');
        Route::get('/edit/{admin:username}', 'AdminController@edit')->name('edit');
        Route::post('/edit/{admin}', 'AdminController@update')->name('update');
        Route::post('/delete', 'AdminController@delete')->name('delete2');
        Route::get('/delete/{admin}', 'AdminController@destroy')->name('admin.destroy');
    });

    Route::prefix('staff')->name('staff.')->group(function (){
        Route::get('/','StaffController@index')->name('index');
        Route::get('/create' , 'StaffController@create')->name('create');
        Route::post('/store','StaffController@store')->name('store');
        Route::get('/edit/{staff:username}' , 'StaffController@edit')->name('edit');
        Route::post('/update/{staff}' , 'StaffController@update')->name('update');
        Route::post('/delete2' , 'StaffController@delete2')->name('delete2');
        Route::get('/destroy/{staff}' , 'StaffController@destroy')->name('destroy');
    });
});

resources/views/layouts/partials/_assets.blade.php
<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="/global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
<link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
<link href="/assets/css/layout.min.css" rel="stylesheet" type="text/css">
<link href="/assets/css/components.min.css" rel="stylesheet" type="text/css">
<link href="/assets/css/colors.min.css" rel="stylesheet" type="text/css">
<!-- /global stylesheets -->

<!-- Core JS files -->
<script src="/global_assets/js/main/jquery.min.js"></script>
<script src="/global_assets/js/main/bootstrap.bundle.min.js"></script>
<script src="/global_assets/js/plugins/loaders/blockui.min.js"></script>
<!-- /core JS files -->

<script src="/global_assets/js/plugins/notifications/sweet_alert.min.js"></script>
<script src="/global_assets/js/demo_pages/alert.js"></script>

resources/views/layouts/partials/_footer.blade.php
<!-- Footer -->
<div class="navbar navbar-expand-lg navbar-light text-center">
     <div class="text-center d-lg-none w-100">
          <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse"
               data-target="#navbar-footer">
               <i class="icon-unfold mr-2"></i>
               Footer
          </button>
     </div>

     <div class="navbar-collapse collapse" style="margin-left: 43%" id="navbar-footer">
          <span class="navbar-text">
               &copy; 2020. <a href="#">Sistem Pendukung Keputusan Kelayakan Pemberian Kredit</a>
          </span>
     </div>
</div>
<!-- /footer -->

resources/views/layouts/partials/_navbar.blade.php
<!-- Main navbar -->
<div class="navbar navbar-expand-md navbar-dark bg-blue-700 fixed-top">
     <div class="navbar-brand wmin-200">
          <a href="index.html" class="d-inline-block">
               <img src="/global_assets/images/logo_light.png" alt="">
          </a>
     </div>

     <div class="d-md-none">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
               <i class="icon-tree5"></i>
          </button>
          <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
               <i class="icon-paragraph-justify3"></i>
          </button>
     </div>

     <div class="collapse navbar-collapse" id="navbar-mobile">
          <ul class="navbar-nav">
               <li class="nav-item">
                    <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                         <i class="icon-paragraph-justify3"></i>
                    </a>
               </li>

               <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                         <img src="/global_assets/images/lang/gb.png" class="img-flag mr-2" alt="">
                         English
                    </a>

                    <div class="dropdown-menu">
                         <a href="#" class="dropdown-item english"><img
                                   src="/global_assets/images/lang/gb.png" class="img-flag" alt="">
                              English</a>
                         <a href="#" class="dropdown-item ukrainian"><img
                                   src="/global_assets/images/lang/ua.png" class="img-flag" alt="">
                              Українська</a>
                         <a href="#" class="dropdown-item deutsch"><img
                                   src="/global_assets/images/lang/de.png" class="img-flag" alt="">
                              Deutsch</a>
                         <a href="#" class="dropdown-item espana"><img
                                   src="/global_assets/images/lang/es.png" class="img-flag" alt="">
                              España</a>
                         <a href="#" class="dropdown-item russian"><img
                                   src="/global_assets/images/lang/ru.png" class="img-flag" alt="">
                              Русский</a>
                    </div>
               </li>
          </ul>

          <span class="badge bg-light shadow-1 text-indigo-700 ml-md-auto mr-md-3">Active</span>

          <ul class="navbar-nav">
               <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
                         <i class="icon-bell2"></i>
                         <span class="d-md-none ml-2">Activity</span>
                         <span class="badge badge-pill badge-mark border-orange-400 ml-auto ml-md-0"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                         <div class="dropdown-content-header">
                              <span class="font-weight-semibold">Latest activity</span>
                              <a href="#" class="text-default"><i class="icon-search4 font-size-base"></i></a>
                         </div>

                         <div class="dropdown-content-body dropdown-scrollable">
                              <ul class="media-list">
                                   <li class="media">
                                        <div class="mr-3">
                                             <a href="#" class="btn bg-success-400 rounded-round btn-icon"><i
                                                       class="icon-mention"></i></a>
                                        </div>

                                        <div class="media-body">
                                             <a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and
                                             tricks"
                                             <div class="font-size-sm text-muted mt-1">4 minutes ago</div>
                                        </div>
                                   </li>

                                   <li class="media">
                                        <div class="mr-3">
                                             <a href="#" class="btn bg-pink-400 rounded-round btn-icon"><i
                                                       class="icon-paperplane"></i></a>
                                        </div>

                                        <div class="media-body">
                                             Special offers have been sent to subscribed users by <a href="#">Donna
                                                  Gordon</a>
                                             <div class="font-size-sm text-muted mt-1">36 minutes ago</div>
                                        </div>
                                   </li>

                                   <li class="media">
                                        <div class="mr-3">
                                             <a href="#" class="btn bg-blue rounded-round btn-icon"><i
                                                       class="icon-plus3"></i></a>
                                        </div>

                                        <div class="media-body">
                                             <a href="#">Chris Arney</a> created a new <span
                                                  class="font-weight-semibold">Design</span> branch in <span
                                                  class="font-weight-semibold">Limitless</span> repository
                                             <div class="font-size-sm text-muted mt-1">2 hours ago</div>
                                        </div>
                                   </li>

                                   <li class="media">
                                        <div class="mr-3">
                                             <a href="#" class="btn bg-purple-300 rounded-round btn-icon"><i
                                                       class="icon-truck"></i></a>
                                        </div>

                                        <div class="media-body">
                                             Shipping cost to the Netherlands has been reduced, database updated
                                             <div class="font-size-sm text-muted mt-1">Feb 8, 11:30</div>
                                        </div>
                                   </li>

                                   <li class="media">
                                        <div class="mr-3">
                                             <a href="#" class="btn bg-warning-400 rounded-round btn-icon"><i
                                                       class="icon-comment"></i></a>
                                        </div>

                                        <div class="media-body">
                                             New review received on <a href="#">Server side integration</a> services
                                             <div class="font-size-sm text-muted mt-1">Feb 2, 10:20</div>
                                        </div>
                                   </li>

                                   <li class="media">
                                        <div class="mr-3">
                                             <a href="#" class="btn bg-teal-400 rounded-round btn-icon"><i
                                                       class="icon-spinner11"></i></a>
                                        </div>

                                        <div class="media-body">
                                             <strong>January, 2018</strong> - 1320 new users, 3284 orders, $49,390
                                             revenue
                                             <div class="font-size-sm text-muted mt-1">Feb 1, 05:46</div>
                                        </div>
                                   </li>
                              </ul>
                         </div>

                         <div class="dropdown-content-footer bg-light">
                              <a href="#" class="text-grey mr-auto">All activity</a>
                              <div>
                                   <a href="#" class="text-grey" data-popup="tooltip" title="Clear list"><i
                                             class="icon-checkmark3"></i></a>
                                   <a href="#" class="text-grey ml-2" data-popup="tooltip" title="Settings"><i
                                             class="icon-gear"></i></a>
                              </div>
                         </div>
                    </div>
               </li>

               <li class="nav-item dropdown dropdown-user">
                    <a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle"
                         data-toggle="dropdown">
                         <img src="global_assets/images/placeholders/placeholder.jpg"
                              class="rounded-circle mr-2" height="34" alt="">
                         <span>Victoria</span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                         <a href="#" class="dropdown-item"><i class="icon-user-plus"></i> My profile</a>
                         <a href="#" class="dropdown-item"><i class="icon-coins"></i> My balance</a>
                         <a href="#" class="dropdown-item"><i class="icon-comment-discussion"></i> Messages <span
                                   class="badge badge-pill bg-blue ml-auto">58</span></a>
                         <div class="dropdown-divider"></div>
                         <a href="#" class="dropdown-item"><i class="icon-cog5"></i> Account settings</a>
                         <a href="#" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
                    </div>
               </li>
          </ul>
     </div>
</div>
<!-- /main navbar -->

resources/views/layouts/partials/_sidebar.blade.php
<!-- Sidebar content -->
<div class="sidebar-content">

     {{-- <!-- User menu -->
     <div class="sidebar-user-material">
          <div class="sidebar-user-material-body card-img-top">
               <div class="card-body text-center">
                    <a href="#">
                         <img src="/global_assets/images/placeholders/placeholder.jpg"
                              class="img-fluid rounded-circle shadow-2 mb-3" width="80" height="80" alt="">
                    </a>
                    <h6 class="mb-0 text-white text-shadow-dark">Victoria Baker</h6>
                    <span class="font-size-sm text-white text-shadow-dark">Santa Ana, CA</span>
               </div>

               <div class="sidebar-user-material-footer">
                    <a href="#user-nav"
                         class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle"
                         data-toggle="collapse"><span>My account</span></a>
               </div>
          </div>

          <div class="collapse" id="user-nav">
               <ul class="nav nav-sidebar">
                    <li class="nav-item">
                         <a href="#" class="nav-link">
                              <i class="icon-user-plus"></i>
                              <span>My profile</span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="#" class="nav-link">
                              <i class="icon-coins"></i>
                              <span>My balance</span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="#" class="nav-link">
                              <i class="icon-comment-discussion"></i>
                              <span>Messages</span>
                              <span class="badge bg-success-400 badge-pill align-self-center ml-auto">58</span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="#" class="nav-link">
                              <i class="icon-cog5"></i>
                              <span>Account settings</span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="#" class="nav-link">
                              <i class="icon-switch2"></i>
                              <span>Logout</span>
                         </a>
                    </li>
               </ul>
          </div>
     </div>
     <!-- /user menu --> --}}


     <!-- Navigation -->
     <div class="card card-sidebar-mobile ">

          <div class="card-body p-0">
               <ul class="nav nav-sidebar" data-nav-type="accordion">
                    <li class="nav-item">
                         <a href="{{ route('dashboard') }}" class="nav-link">
                              <i class="icon-home4"></i>
                              <span>
                                   Dashboard
                              </span>
                         </a>
                    </li>
                    @role('superadmin')
                    <li class="nav-item">
                         <a href="{{ route('superadmin.admin.index') }}" class="nav-link">
                              <i class="icon-user"></i>
                              <span>
                                   Admin
                              </span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="{{ route('superadmin.staff.index') }}" class="nav-link">
                              <i class="icon-users"></i>
                              <span>
                                   Staff
                              </span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="{{ route('superadmin.admin.index') }}" class="nav-link">
                              <i class="icon-users2"></i>
                              <span>
                                   Nasabah
                              </span>
                         </a>
                    </li>
                    <li class="nav-item">
                         <a href="{{ route('superadmin.admin.index') }}" class="nav-link">
                              <i class="icon-office"></i>
                              <span>
                                   Simpanan
                              </span>
                         </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('superadmin.admin.index') }}" class="nav-link">
                              <i class="icon-office"></i>
                              <span>
                                   Pinjaman
                              </span>
                         </a>
                    </li>
                    <li class="nav-item nav-item-submenu">
                         <a href="#" class="nav-link"><i class="icon-book"></i> <span>Laporan</span></a>

                         <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                              <li class="nav-item"><a href="#" class="nav-link">Laporan Peminjam</a>
                              </li>
                              <li class="nav-item"><a href="#" class="nav-link">Laporan Kelayakan</a>
                              </li>
                         </ul>
                    </li>
                    @endrole

                    @role('admin')

                    @endrole
               </ul>
          </div>
     </div>
     <!-- /navigation -->

</div>
<!-- /sidebar content -->